# Project: ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex.o ic_0301_05_10_2020_Fabiola_Morales_Antonio_app.o
LINKOBJ  = ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex.o ic_0301_05_10_2020_Fabiola_Morales_Antonio_app.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib"
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex.o: ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex.c
	$(CC) -c ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex.c -o ic_0301_05_10_2020_Fabiola_Morales_Antonio_simplex.o $(CFLAGS)

ic_0301_05_10_2020_Fabiola_Morales_Antonio_app.o: ic_0301_05_10_2020_Fabiola_Morales_Antonio_app.c
	$(CC) -c ic_0301_05_10_2020_Fabiola_Morales_Antonio_app.c -o ic_0301_05_10_2020_Fabiola_Morales_Antonio_app.o $(CFLAGS)
